name: Django CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
    - name: Check out the code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Check Python version
      run: python --version

    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('SAMS/requirements.txt') }}-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r SAMS/requirements.txt
        pip install coverage

    - name: Set up the database
      run: |
        cd SAMS  # Ensure we are in the correct directory
        export DJANGO_SETTINGS_MODULE=SAMS.settings  # Explicitly set the settings module here as well
        python manage.py migrate --noinput
        python manage.py showmigrations  # Debugging step to check if migrations are applied

    - name: Run tests with coverage
      run: |
        cd SAMS  # Ensure we are in the correct directory
        export DJANGO_SETTINGS_MODULE=SAMS.settings  # Set the settings module again
        coverage run --source='.' manage.py test --verbosity 2
        coverage report --fail-under=60
        coverage xml

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: true
